### ISSUE TITLE
Language Provider?!?!?!?!!?

### ISSUE THREAD

**Issue by Witzloser** [Bl4ues/SCP-Additions#1]
The mods Doesnt Work cuz of the Language Provider...

Crash Log:
[19:18:00] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [

Mod File Kleiders+Custom+Renderer+API+5.5.1+1.20.1.jar needs language provider javafml:47 or above to load

§7We have found 36.2,

Mod §ekleiders_custom_renderer§r requires §6minecraft§r §o1.20.1§r

§7Currently, §6minecraft§r§7 is §o1.16.5

]

at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[forge:?] {re:classloading}

at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:30) ~[forge:?] {re:classloading}

at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}

at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[server.jar:36.2] {}

at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [server.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [server.jar:?] {}

at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [server.jar:?] {}

**Comment by Witzloser** [comment]
I just saw it is from Kleiders Custom Renderer can you help me there too?

**Comment by Bl4ues** [comment]
Kleiders Custom Renderer API is a required dependency of the mod because of a feature of the WIP SCP-914. Did you have the mod installed?
https://www.curseforge.com/minecraft/mc-mods/kleiders-custom-renderer-api

**Comment by Bl4ues** [comment]
Just saw you did have KCR, but you downloaded for the version 1.20.1
You should download this one instead: https://www.curseforge.com/minecraft/mc-mods/kleiders-custom-renderer-api/files/4478424

**Comment by Witzloser** [comment]
You did it works now, thanks! but now i have a Second Problem :() The SCP Keycard Mod is bugged, it says: requires §6forge§r §o36.2.26§r
§7Currently, §6forge§r§7 is §o36.2.39


Full Error Log:
[21:40:10] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [

Mod §escp_keycards§r requires §6forge§r §o36.2.26§r

§7Currently, §6forge§r§7 is §o36.2.39

]

at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[forge:?] {re:classloading}

at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:30) ~[forge:?] {re:classloading}

at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}

at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[server.jar:36.2] {}

at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}

at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [server.jar:?] {}

at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [server.jar:?] {}

at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [server.jar:?] {}

**Comment by Witzloser** [comment]
I don't know how to change the forge version

**Comment by Bl4ues** [comment]
You need to download it on the forge website: https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html
You then need to download the 36.2.26 version and install it in the place of 36.2.39.
If you have doubts on how to dowload and install forge on minecraft, you can take a look at some tutorials.
